#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
NEOLOGD_ROOT="${1:-$ROOT_DIR/dic/mecab-ipadic-neologd-0.0.7}"
LIMIT="${2:-5000}"
SEED_DIR="$NEOLOGD_ROOT/seed"
CACHE_DIR="$ROOT_DIR/tools/dict-compiler/.cache/neologd"
TSV_PATH="$CACHE_DIR/neologd_rows.tsv"
SORTED_TSV="$CACHE_DIR/neologd_rows.sorted.tsv"
OUT_PATH="$ROOT_DIR/src/dict/full/dict_neologd_generated.mbt"

if [[ ! -d "$SEED_DIR" ]]; then
  echo "[neologd] seed directory not found: $SEED_DIR" >&2
  exit 1
fi

mkdir -p "$CACHE_DIR"

echo "[neologd] extracting lexical rows from: $SEED_DIR (limit=$LIMIT)..."
xzcat "$SEED_DIR"/*.csv.xz | awk -F',' -v limit="$LIMIT" '
BEGIN {
  OFS = "\t";
  count = 0;
}
{
  if (count >= limit) next;
  surface = $1;
  left_id = $2;
  right_id = $3;
  word_cost = $4;
  pos1 = $5;
  pos2 = $6;
  pos3 = $7;
  pos4 = $8;
  ctype = ($9 == "" ? "*" : $9);
  cform = ($10 == "" ? "*" : $10);
  base = ($11 == "" ? surface : $11);
  read = ($12 == "" ? "*" : $12);
  pron = ($13 == "" ? "*" : $13);
  tag = "";
  if (pos1 == "名詞") {
    if (pos2 == "固有名詞") tag = "NOUN_PROPER";
    else if (pos2 == "非自立") tag = "NOUN_NON_INDEPENDENT";
    else tag = "NOUN_GENERAL";
  } else if (pos1 == "助詞") {
    tag = "PARTICLE";
  } else {
    next;
  }
  print surface, tag, left_id, right_id, word_cost, pos1, pos2, pos3, pos4, ctype, cform, base, read, pron;
  count++;
}
END {
  printf("[neologd] accepted rows: %d\n", count) > "/dev/stderr";
}
' > "$TSV_PATH"

LC_ALL=C sort -t $'\t' -k1,1 "$TSV_PATH" > "$SORTED_TSV"

{
  echo "///|"
  echo "/// Auto-generated by tools/dict-compiler/scripts/build_neologd_generated.sh"
  echo "/// Source: $NEOLOGD_ROOT"
  echo "/// Rows: $LIMIT (filtered by POS)"
  echo "type DictEntry = @types.DictEntry"
  echo
  echo "///|"
  echo "type POS = @types.POS"
  echo
  echo "///|"
  echo "let neologd_entries_generated : ReadOnlyArray[DictEntry] = ["
} > "$OUT_PATH"

awk -F'\t' '
function escape(s) {
  gsub(/\\/, "\\\\", s);
  gsub(/"/, "\\\"", s);
  return s;
}
function pos_expr(tag) {
  if (tag == "NOUN_GENERAL") return "POS::NounGeneral";
  if (tag == "NOUN_PROPER") return "POS::NounProper";
  if (tag == "NOUN_NON_INDEPENDENT") return "POS::NounNonIndependent";
  if (tag == "PARTICLE") return "POS::Particle";
  return "POS::Unknown";
}
{
  surface = escape($1);
  pos = pos_expr($2);
  left_id = $3;
  right_id = $4;
  word_cost = $5;
  pos1 = $6;
  pos2 = $7;
  pos3 = $8;
  pos4 = $9;
  ctype = ($10 == "" ? "*" : $10);
  cform = ($11 == "" ? "*" : $11);
  base = ($12 == "" ? $1 : $12);
  read = ($13 == "" ? "*" : $13);
  pron = ($14 == "" ? "*" : $14);
  printf("  { surface: \"%s\", pos: %s, pos_detail: \"%s,%s,%s,%s\", mecab_feature: \"%s,%s,%s,%s,%s,%s,%s,%s,%s\", left_id: %s, right_id: %s, word_cost: %s },\n",
    surface, pos, pos1, pos2, pos3, pos4, pos1, pos2, pos3, pos4, ctype, cform, base, read, pron, left_id, right_id, word_cost);
}
' "$SORTED_TSV" >> "$OUT_PATH"

{
  echo "]"
} >> "$OUT_PATH"

(
  cd "$ROOT_DIR"
  moon run --target native tools/dict-compiler/cmd/emit_da neologd_da full < "$SORTED_TSV"
) >> "$OUT_PATH"

echo "[neologd] generated: $OUT_PATH"
