#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
IPADIC_ROOT="${1:-$ROOT_DIR/tools/dict-compiler/.cache/ipadic/mecab-ipadic-2.7.0-20070801}"
IPADIC_TSV="${2:-$ROOT_DIR/tools/dict-compiler/.cache/ipadic/ipadic_rows.tsv}"
NEOLOGD_TSV="${3:-$ROOT_DIR/tools/dict-compiler/.cache/neologd/neologd_rows.tsv}"
OUT_PATH="$ROOT_DIR/src/dict/standard/dict_connection_generated.mbt"
CACHE_DIR="$ROOT_DIR/tools/dict-compiler/.cache/connection"
MATRIX_DEF="$IPADIC_ROOT/matrix.def"
IDS_PATH="$CACHE_DIR/ids.txt"

if [[ ! -f "$MATRIX_DEF" ]]; then
  echo "[connection] matrix.def not found: $MATRIX_DEF" >&2
  exit 1
fi

mkdir -p "$CACHE_DIR"

{
  echo 0
  echo 1
  echo 2
  echo 3
  if [[ -f "$IPADIC_TSV" ]]; then
    awk -F'\t' '{ print $3 "\n" $4 }' "$IPADIC_TSV"
  fi
  if [[ -f "$NEOLOGD_TSV" ]]; then
    awk -F'\t' '{ print $3 "\n" $4 }' "$NEOLOGD_TSV"
  fi
} | awk 'NF > 0 { print $1 }' | sort -n | uniq > "$IDS_PATH"

NUM_IDS="$(wc -l < "$IDS_PATH" | tr -d ' ')"
MAX_ID="$(tail -n 1 "$IDS_PATH")"
if [[ -z "$MAX_ID" ]]; then
  MAX_ID=3
fi

echo "[connection] ids: $NUM_IDS (max=$MAX_ID)"

{
  echo "///|"
  echo "/// Auto-generated by tools/dict-compiler/scripts/build_connection_generated.sh"
  echo "/// Source matrix: $MATRIX_DEF"
  echo "let connection_num_ids = $NUM_IDS"
  echo
  echo "///|"
  echo -n "let connection_id_to_compact : ReadOnlyArray[Int] = ["
  awk -v max="$MAX_ID" '
  BEGIN {
    for (i = 0; i <= max; i++) map[i] = -1;
  }
  {
    id = $1 + 0;
    map[id] = NR - 1;
  }
  END {
    for (i = 0; i <= max; i++) {
      if (i > 0) printf(", ");
      printf("%d", map[i]);
    }
    printf("]\n");
  }
  ' "$IDS_PATH"
  echo
  echo "///|"
  echo "let connection_matrix_compact : ReadOnlyArray[Int] = ["
  awk '
  FNR == NR {
    ids[FNR - 1] = $1 + 0;
    used[$1 + 0] = 1;
    n = FNR;
    next;
  }
  FNR == 1 { next; } # skip matrix header line
  {
    r = $1 + 0;
    l = $2 + 0;
    c = $3 + 0;
    if ((r in used) && (l in used)) {
      key = r ":" l;
      cost[key] = c;
    }
  }
  END {
    default_cost = 10000;
    for (ri = 0; ri < n; ri++) {
      for (li = 0; li < n; li++) {
        key = ids[ri] ":" ids[li];
        v = (key in cost) ? cost[key] : default_cost;
        printf("  %d,\n", v);
      }
    }
  }
  ' "$IDS_PATH" "$MATRIX_DEF"
  echo "]"
} > "$OUT_PATH"

echo "[connection] generated: $OUT_PATH"
