#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"
CACHE_DIR="$ROOT_DIR/tools/dict-compiler/.cache/ipadic"
ARCHIVE_PATH="$CACHE_DIR/mecab-ipadic-2.7.0-20070801.tar.xz"
SRC_DIR="$CACHE_DIR/mecab-ipadic-2.7.0-20070801"
TSV_PATH="$CACHE_DIR/ipadic_rows.tsv"
SORTED_TSV="$CACHE_DIR/ipadic_rows.sorted.tsv"
OUT_PATH="$ROOT_DIR/src/dict/standard/dict_ipadic_generated.mbt"
LIMIT="${1:-5000}"

mkdir -p "$CACHE_DIR"

if [[ ! -f "$ARCHIVE_PATH" ]]; then
  echo "[ipadic] downloading archive..."
  curl -fsSL \
    "https://raw.githubusercontent.com/takuyaa/mecab-ipadic-seed/master/dict/mecab-ipadic-2.7.0-20070801.tar.xz" \
    -o "$ARCHIVE_PATH"
fi

if [[ ! -d "$SRC_DIR" ]]; then
  echo "[ipadic] extracting archive..."
  tar -xf "$ARCHIVE_PATH" -C "$CACHE_DIR"
fi

echo "[ipadic] extracting lexical rows (limit=$LIMIT)..."
awk -F',' -v limit="$LIMIT" '
BEGIN {
  OFS = "\t";
  count = 0;
}
{
  if (count >= limit) next;
  surface = $1;
  left_id = $2;
  right_id = $3;
  word_cost = $4;
  pos1 = $5;
  pos2 = $6;
  pos3 = $7;
  pos4 = $8;
  tag = "";
  if (pos1 == "名詞") {
    if (pos2 == "固有名詞") tag = "NOUN_PROPER";
    else if (pos2 == "非自立") tag = "NOUN_NON_INDEPENDENT";
    else tag = "NOUN_GENERAL";
  } else if (pos1 == "助詞") {
    tag = "PARTICLE";
  } else {
    next;
  }
  print surface, tag, left_id, right_id, word_cost, pos1, pos2, pos3, pos4;
  count++;
}
END {
  printf("[ipadic] accepted rows: %d\n", count) > "/dev/stderr";
}
' "$SRC_DIR"/*.csv > "$TSV_PATH"

LC_ALL=C sort -t $'\t' -k1,1 "$TSV_PATH" > "$SORTED_TSV"

{
  echo "///|"
  echo "/// Auto-generated by tools/dict-compiler/scripts/build_ipadic_generated.sh"
  echo "/// Source: mecab-ipadic-2.7.0-20070801"
  echo "/// Rows: $LIMIT (filtered by POS)"
  echo "type DictEntry = @types.DictEntry"
  echo
  echo "///|"
  echo "type POS = @types.POS"
  echo
  echo "///|"
  echo "let ipadic_entries_generated : ReadOnlyArray[DictEntry] = ["
} > "$OUT_PATH"

awk -F'\t' '
function escape(s) {
  gsub(/\\/, "\\\\", s);
  gsub(/"/, "\\\"", s);
  return s;
}
function pos_expr(tag) {
  if (tag == "NOUN_GENERAL") return "POS::NounGeneral";
  if (tag == "NOUN_PROPER") return "POS::NounProper";
  if (tag == "NOUN_NON_INDEPENDENT") return "POS::NounNonIndependent";
  if (tag == "PARTICLE") return "POS::Particle";
  return "POS::Unknown";
}
{
  surface = escape($1);
  pos = pos_expr($2);
  left_id = $3;
  right_id = $4;
  word_cost = $5;
  pos1 = $6;
  pos2 = $7;
  pos3 = $8;
  pos4 = $9;
  printf("  { surface: \"%s\", pos: %s, pos_detail: \"%s,%s,%s,%s\", left_id: %s, right_id: %s, word_cost: %s },\n",
    surface, pos, pos1, pos2, pos3, pos4, left_id, right_id, word_cost);
}
' "$SORTED_TSV" >> "$OUT_PATH"

{
  echo "]"
} >> "$OUT_PATH"

(
  cd "$ROOT_DIR"
  moon run --target native tools/dict-compiler/cmd/emit_da ipadic_da standard < "$SORTED_TSV"
) >> "$OUT_PATH"

echo "[ipadic] generated: $OUT_PATH"
