///|
let standard_extra_entries : ReadOnlyArray[@types.DictEntry] = [
  {
    surface: "東京都",
    pos: @types.POS::NounProper,
    pos_detail: "名詞,固有名詞,地域,一般",
    left_id: 1,
    right_id: 1,
    word_cost: 500,
  },
  {
    surface: "大学院",
    pos: @types.POS::NounGeneral,
    pos_detail: "名詞,一般,*,*",
    left_id: 1,
    right_id: 1,
    word_cost: 620,
  },
  {
    surface: "自然言語処理",
    pos: @types.POS::NounGeneral,
    pos_detail: "名詞,一般,*,*",
    left_id: 1,
    right_id: 1,
    word_cost: 450,
  },
]
