name = "micado-edge"
main = "src/worker.ts"
compatibility_date = "2026-02-21"
minify = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[rules]]
type = "Data"
globs = ["**/*.deflate"]
fallthrough = true
